enum modifierfunction : uint32_t
{
	// MScriptDescription = "GetModifierPreAttack_BonusDamage"
	MODIFIER_PROPERTY_PREATTACK_BONUS_DAMAGE = 0,
	// MScriptDescription = "GetModifierPreAttack_BonusDamage_Target"
	MODIFIER_PROPERTY_PREATTACK_BONUS_DAMAGE_TARGET = 1,
	// MScriptDescription = "GetModifierPreAttack_BonusDamage_Proc"
	MODIFIER_PROPERTY_PREATTACK_BONUS_DAMAGE_PROC = 2,
	// MScriptDescription = "GetModifierPreAttack_BonusDamagePostCrit"
	MODIFIER_PROPERTY_PREATTACK_BONUS_DAMAGE_POST_CRIT = 3,
	// MScriptDescription = "GetModifierBaseAttack_BonusDamage"
	MODIFIER_PROPERTY_BASEATTACK_BONUSDAMAGE = 4,
	// MScriptDescription = "GetModifierProcAttack_BonusDamage_Physical"
	MODIFIER_PROPERTY_PROCATTACK_BONUS_DAMAGE_PHYSICAL = 5,
	// MScriptDescription = "GetModifierProcAttack_ConvertPhysicalToMagical"
	MODIFIER_PROPERTY_PROCATTACK_CONVERT_PHYSICAL_TO_MAGICAL = 6,
	// MScriptDescription = "GetModifierProcAttack_BonusDamage_Magical"
	MODIFIER_PROPERTY_PROCATTACK_BONUS_DAMAGE_MAGICAL = 7,
	// MScriptDescription = "GetModifierProcAttack_BonusDamage_Pure"
	MODIFIER_PROPERTY_PROCATTACK_BONUS_DAMAGE_PURE = 8,
	// MScriptDescription = "GetModifierProcAttack_BonusDamage_Magical_Target"
	MODIFIER_PROPERTY_PROCATTACK_BONUS_DAMAGE_MAGICAL_TARGET = 9,
	// MScriptDescription = "GetModifierProcAttack_Feedback"
	MODIFIER_PROPERTY_PROCATTACK_FEEDBACK = 10,
	// MScriptDescription = "GetModifierOverrideAttackDamage"
	MODIFIER_PROPERTY_OVERRIDE_ATTACK_DAMAGE = 11,
	// MScriptDescription = "GetModifierPreAttack"
	MODIFIER_PROPERTY_PRE_ATTACK = 12,
	// MScriptDescription = "GetModifierInvisibilityLevel"
	MODIFIER_PROPERTY_INVISIBILITY_LEVEL = 13,
	// MScriptDescription = "GetModifierInvisibilityAttackBehaviorException"
	MODIFIER_PROPERTY_INVISIBILITY_ATTACK_BEHAVIOR_EXCEPTION = 14,
	// MScriptDescription = "GetModifierPersistentInvisibility"
	MODIFIER_PROPERTY_PERSISTENT_INVISIBILITY = 15,
	// MScriptDescription = "GetModifierMoveSpeedBonus_Constant"
	MODIFIER_PROPERTY_MOVESPEED_BONUS_CONSTANT = 16,
	// MScriptDescription = "GetModifierMoveSpeedOverride"
	MODIFIER_PROPERTY_MOVESPEED_BASE_OVERRIDE = 17,
	// MScriptDescription = "GetModifierMoveSpeed_MinOverride"
	MODIFIER_PROPERTY_MOVESPEED_MIN_OVERRIDE = 18,
	// MScriptDescription = "GetModifierMoveSpeed_MaxOverride"
	MODIFIER_PROPERTY_MOVESPEED_MAX_OVERRIDE = 19,
	// MScriptDescription = "GetModifierMoveSpeedBonus_Percentage"
	MODIFIER_PROPERTY_MOVESPEED_BONUS_PERCENTAGE = 20,
	// MScriptDescription = "GetModifierMoveSpeedBonus_Percentage_Unique"
	MODIFIER_PROPERTY_MOVESPEED_BONUS_PERCENTAGE_UNIQUE = 21,
	// MScriptDescription = "GetModifierMoveSpeedBonus_Special_Boots"
	MODIFIER_PROPERTY_MOVESPEED_BONUS_UNIQUE = 22,
	// MScriptDescription = "GetModifierMoveSpeedBonus_Special_Boots_2"
	MODIFIER_PROPERTY_MOVESPEED_BONUS_UNIQUE_2 = 23,
	// MScriptDescription = "GetModifierMoveSpeedBonus_Constant_Unique"
	MODIFIER_PROPERTY_MOVESPEED_BONUS_CONSTANT_UNIQUE = 24,
	// MScriptDescription = "GetModifierMoveSpeedBonus_Constant_Unique_2"
	MODIFIER_PROPERTY_MOVESPEED_BONUS_CONSTANT_UNIQUE_2 = 25,
	// MScriptDescription = "GetModifierMoveSpeed_Absolute"
	MODIFIER_PROPERTY_MOVESPEED_ABSOLUTE = 26,
	// MScriptDescription = "GetModifierMoveSpeed_AbsoluteMin"
	MODIFIER_PROPERTY_MOVESPEED_ABSOLUTE_MIN = 27,
	// MScriptDescription = "GetModifierMoveSpeed_AbsoluteMax"
	MODIFIER_PROPERTY_MOVESPEED_ABSOLUTE_MAX = 28,
	// MScriptDescription = "GetModifierIgnoreMovespeedLimit"
	MODIFIER_PROPERTY_IGNORE_MOVESPEED_LIMIT = 29,
	// MScriptDescription = "GetModifierMoveSpeed_Limit"
	MODIFIER_PROPERTY_MOVESPEED_LIMIT = 30,
	// MScriptDescription = "GetModifierAttackSpeedBaseOverride"
	MODIFIER_PROPERTY_ATTACKSPEED_BASE_OVERRIDE = 31,
	// MScriptDescription = "GetModifierFixedAttackRate"
	MODIFIER_PROPERTY_FIXED_ATTACK_RATE = 32,
	// MScriptDescription = "GetModifierAttackSpeedBonus_Constant"
	MODIFIER_PROPERTY_ATTACKSPEED_BONUS_CONSTANT = 33,
	// MScriptDescription = "GetModifierAttackSpeed_Limit"
	MODIFIER_PROPERTY_IGNORE_ATTACKSPEED_LIMIT = 34,
	// MScriptDescription = "GetModifierCooldownReduction_Constant"
	MODIFIER_PROPERTY_COOLDOWN_REDUCTION_CONSTANT = 35,
	// MScriptDescription = "GetModifierManacostReduction_Constant"
	MODIFIER_PROPERTY_MANACOST_REDUCTION_CONSTANT = 36,
	// MScriptDescription = "GetModifierHealthcostReduction_Constant"
	MODIFIER_PROPERTY_HEALTHCOST_REDUCTION_CONSTANT = 37,
	// MScriptDescription = "GetModifierBaseAttackTimeConstant"
	MODIFIER_PROPERTY_BASE_ATTACK_TIME_CONSTANT = 38,
	// MScriptDescription = "GetModifierBaseAttackTimeConstant_Adjust"
	MODIFIER_PROPERTY_BASE_ATTACK_TIME_CONSTANT_ADJUST = 39,
	// MScriptDescription = "GetModifierBaseAttackTimePercentage"
	MODIFIER_PROPERTY_BASE_ATTACK_TIME_PERCENTAGE = 40,
	// MScriptDescription = "GetModifierAttackPointConstant"
	MODIFIER_PROPERTY_ATTACK_POINT_CONSTANT = 41,
	// MScriptDescription = "GetModifierBonusDamageOutgoing_Percentage"
	MODIFIER_PROPERTY_BONUSDAMAGEOUTGOING_PERCENTAGE = 42,
	// MScriptDescription = "GetModifierDamageOutgoing_Percentage"
	MODIFIER_PROPERTY_DAMAGEOUTGOING_PERCENTAGE = 43,
	// MScriptDescription = "GetModifierDamageOutgoing_Percentage_Illusion"
	MODIFIER_PROPERTY_DAMAGEOUTGOING_PERCENTAGE_ILLUSION = 44,
	// MScriptDescription = "GetModifierDamageOutgoing_Percentage_Illusion_Amplify"
	MODIFIER_PROPERTY_DAMAGEOUTGOING_PERCENTAGE_ILLUSION_AMPLIFY = 45,
	// MScriptDescription = "GetModifierTotalDamageOutgoing_Percentage"
	MODIFIER_PROPERTY_TOTALDAMAGEOUTGOING_PERCENTAGE = 46,
	// MScriptDescription = "GetModifierSpellAmplify_Percentage"
	MODIFIER_PROPERTY_SPELL_AMPLIFY_PERCENTAGE = 47,
	// MScriptDescription = "GetModifierSpellAmplify_PercentageUnique"
	MODIFIER_PROPERTY_SPELL_AMPLIFY_PERCENTAGE_UNIQUE = 48,
	// MScriptDescription = "GetModifierSpellAmplify_PercentageUnique_2"
	MODIFIER_PROPERTY_SPELL_AMPLIFY_PERCENTAGE_UNIQUE_2 = 49,
	// MScriptDescription = "GetModifierSpellAmplify_PercentageTarget"
	MODIFIER_PROPERTY_SPELL_AMPLIFY_PERCENTAGE_TARGET = 50,
	// MScriptDescription = "GetModifierHealAmplify_PercentageSource"
	MODIFIER_PROPERTY_HEAL_AMPLIFY_PERCENTAGE_SOURCE = 51,
	// MScriptDescription = "GetModifierHealAmplify_PercentageTarget"
	MODIFIER_PROPERTY_HEAL_AMPLIFY_PERCENTAGE_TARGET = 52,
	// MScriptDescription = "GetModifierHPRegenAmplify_Percentage"
	MODIFIER_PROPERTY_HP_REGEN_AMPLIFY_PERCENTAGE = 53,
	// MScriptDescription = "GetModifierLifestealRegenAmplify_Percentage"
	MODIFIER_PROPERTY_LIFESTEAL_AMPLIFY_PERCENTAGE = 54,
	// MScriptDescription = "GetModifierSpellLifestealRegenAmplify_Percentage"
	MODIFIER_PROPERTY_SPELL_LIFESTEAL_AMPLIFY_PERCENTAGE = 55,
	// MScriptDescription = "GetModifierSpellLifestealRegenAmplify_Percentage_Unique"
	MODIFIER_PROPERTY_SPELL_LIFESTEAL_AMPLIFY_PERCENTAGE_UNIQUE = 56,
	// MScriptDescription = "GetModifierMPRegenAmplify_Percentage"
	MODIFIER_PROPERTY_MP_REGEN_AMPLIFY_PERCENTAGE = 57,
	// MScriptDescription = "GetModifierMPRegenAmplify_Percentage_Unique"
	MODIFIER_PROPERTY_MP_REGEN_AMPLIFY_PERCENTAGE_UNIQUE = 58,
	// MScriptDescription = "GetModifierManaDrainAmplify_Percentage"
	MODIFIER_PROPERTY_MANA_DRAIN_AMPLIFY_PERCENTAGE = 59,
	// MScriptDescription = "GetModifierMPRestoreAmplify_Percentage"
	MODIFIER_PROPERTY_MP_RESTORE_AMPLIFY_PERCENTAGE = 60,
	// MScriptDescription = "GetModifierBaseDamageOutgoing_Percentage"
	MODIFIER_PROPERTY_BASEDAMAGEOUTGOING_PERCENTAGE = 61,
	// MScriptDescription = "GetModifierBaseDamageOutgoing_PercentageUnique"
	MODIFIER_PROPERTY_BASEDAMAGEOUTGOING_PERCENTAGE_UNIQUE = 62,
	// MScriptDescription = "GetModifierIncomingDamage_Percentage"
	MODIFIER_PROPERTY_INCOMING_DAMAGE_PERCENTAGE = 63,
	// MScriptDescription = "GetModifierIncomingPhysicalDamage_Percentage"
	MODIFIER_PROPERTY_INCOMING_PHYSICAL_DAMAGE_PERCENTAGE = 64,
	// MScriptDescription = "GetModifierIncomingPhysicalDamageConstant"
	MODIFIER_PROPERTY_INCOMING_PHYSICAL_DAMAGE_CONSTANT = 65,
	// MScriptDescription = "GetModifierIncomingSpellDamageConstant"
	MODIFIER_PROPERTY_INCOMING_SPELL_DAMAGE_CONSTANT = 66,
	// MScriptDescription = "GetModifierEvasion_Constant"
	MODIFIER_PROPERTY_EVASION_CONSTANT = 67,
	// MScriptDescription = "GetModifierNegativeEvasion_Constant"
	MODIFIER_PROPERTY_NEGATIVE_EVASION_CONSTANT = 68,
	// MScriptDescription = "GetModifierStatusResistance"
	MODIFIER_PROPERTY_STATUS_RESISTANCE = 69,
	// MScriptDescription = "GetModifierStatusResistanceStacking"
	MODIFIER_PROPERTY_STATUS_RESISTANCE_STACKING = 70,
	// MScriptDescription = "GetModifierStatusResistanceCaster"
	MODIFIER_PROPERTY_STATUS_RESISTANCE_CASTER = 71,
	// MScriptDescription = "GetModifierAvoidDamage"
	MODIFIER_PROPERTY_AVOID_DAMAGE = 72,
	// MScriptDescription = "GetModifierAvoidSpell"
	MODIFIER_PROPERTY_AVOID_SPELL = 73,
	// MScriptDescription = "GetModifierMiss_Percentage"
	MODIFIER_PROPERTY_MISS_PERCENTAGE = 74,
	// MScriptDescription = "GetModifierPhysicalArmorBase_Percentage"
	MODIFIER_PROPERTY_PHYSICAL_ARMOR_BASE_PERCENTAGE = 75,
	// MScriptDescription = "GetModifierPhysicalArmorTotal_Percentage"
	MODIFIER_PROPERTY_PHYSICAL_ARMOR_TOTAL_PERCENTAGE = 76,
	// MScriptDescription = "GetModifierPhysicalArmorBonus"
	MODIFIER_PROPERTY_PHYSICAL_ARMOR_BONUS = 77,
	// MScriptDescription = "GetModifierPhysicalArmorBonusUnique"
	MODIFIER_PROPERTY_PHYSICAL_ARMOR_BONUS_UNIQUE = 78,
	// MScriptDescription = "GetModifierPhysicalArmorBonusUniqueActive"
	MODIFIER_PROPERTY_PHYSICAL_ARMOR_BONUS_UNIQUE_ACTIVE = 79,
	// MScriptDescription = "GetModifierPhysicalArmorBonusPost"
	MODIFIER_PROPERTY_PHYSICAL_ARMOR_BONUS_POST = 80,
	// MScriptDescription = "GetModifierMinPhysicalArmor"
	MODIFIER_PROPERTY_MIN_PHYSICAL_ARMOR = 81,
	// MScriptDescription = "GetModifierIgnorePhysicalArmor"
	MODIFIER_PROPERTY_IGNORE_PHYSICAL_ARMOR = 82,
	// MScriptDescription = "GetModifierMagicalResistanceBaseReduction"
	MODIFIER_PROPERTY_MAGICAL_RESISTANCE_BASE_REDUCTION = 83,
	// MScriptDescription = "GetModifierMagicalResistanceDirectModification"
	MODIFIER_PROPERTY_MAGICAL_RESISTANCE_DIRECT_MODIFICATION = 84,
	// MScriptDescription = "GetModifierMagicalResistanceBonus"
	MODIFIER_PROPERTY_MAGICAL_RESISTANCE_BONUS = 85,
	// MScriptDescription = "GetModifierMagicalResistanceBonusIllusions"
	MODIFIER_PROPERTY_MAGICAL_RESISTANCE_BONUS_ILLUSIONS = 86,
	// MScriptDescription = "GetModifierMagicalResistanceBonusUnique"
	MODIFIER_PROPERTY_MAGICAL_RESISTANCE_BONUS_UNIQUE = 87,
	// MScriptDescription = "GetModifierMagicalResistanceDecrepifyUnique"
	MODIFIER_PROPERTY_MAGICAL_RESISTANCE_DECREPIFY_UNIQUE = 88,
	// MScriptDescription = "GetModifierBaseRegen"
	MODIFIER_PROPERTY_BASE_MANA_REGEN = 89,
	// MScriptDescription = "GetModifierConstantManaRegen"
	MODIFIER_PROPERTY_MANA_REGEN_CONSTANT = 90,
	// MScriptDescription = "GetModifierConstantManaRegenUnique"
	MODIFIER_PROPERTY_MANA_REGEN_CONSTANT_UNIQUE = 91,
	// MScriptDescription = "GetModifierTotalPercentageManaRegen"
	MODIFIER_PROPERTY_MANA_REGEN_TOTAL_PERCENTAGE = 92,
	// MScriptDescription = "GetModifierConstantHealthRegen"
	MODIFIER_PROPERTY_HEALTH_REGEN_CONSTANT = 93,
	// MScriptDescription = "GetModifierHealthRegenPercentage"
	MODIFIER_PROPERTY_HEALTH_REGEN_PERCENTAGE = 94,
	// MScriptDescription = "GetModifierHealthRegenPercentageUnique"
	MODIFIER_PROPERTY_HEALTH_REGEN_PERCENTAGE_UNIQUE = 95,
	// MScriptDescription = "GetModifierHealthBonus"
	MODIFIER_PROPERTY_HEALTH_BONUS = 96,
	// MScriptDescription = "GetModifierManaBonus"
	MODIFIER_PROPERTY_MANA_BONUS = 97,
	// MScriptDescription = "GetModifierExtraStrengthBonus"
	MODIFIER_PROPERTY_EXTRA_STRENGTH_BONUS = 98,
	// MScriptDescription = "GetModifierExtraHealthBonus"
	MODIFIER_PROPERTY_EXTRA_HEALTH_BONUS = 99,
	// MScriptDescription = "GetModifierExtraManaBonus"
	MODIFIER_PROPERTY_EXTRA_MANA_BONUS = 100,
	// MScriptDescription = "GetModifierExtraManaBonusPercentage"
	MODIFIER_PROPERTY_EXTRA_MANA_BONUS_PERCENTAGE = 101,
	// MScriptDescription = "GetModifierExtraHealthPercentage"
	MODIFIER_PROPERTY_EXTRA_HEALTH_PERCENTAGE = 102,
	// MScriptDescription = "GetModifierExtraManaPercentage"
	MODIFIER_PROPERTY_EXTRA_MANA_PERCENTAGE = 103,
	// MScriptDescription = "GetModifierBonusStats_Strength"
	MODIFIER_PROPERTY_STATS_STRENGTH_BONUS = 104,
	// MScriptDescription = "GetModifierBonusStats_Agility"
	MODIFIER_PROPERTY_STATS_AGILITY_BONUS = 105,
	// MScriptDescription = "GetModifierBonusStats_Intellect"
	MODIFIER_PROPERTY_STATS_INTELLECT_BONUS = 106,
	// MScriptDescription = "GetModifierBonusStats_Strength_Percentage"
	MODIFIER_PROPERTY_STATS_STRENGTH_BONUS_PERCENTAGE = 107,
	// MScriptDescription = "GetModifierBonusStats_Agility_Percentage"
	MODIFIER_PROPERTY_STATS_AGILITY_BONUS_PERCENTAGE = 108,
	// MScriptDescription = "GetModifierBonusStats_Intellect_Percentage"
	MODIFIER_PROPERTY_STATS_INTELLECT_BONUS_PERCENTAGE = 109,
	// MScriptDescription = "GetModifierIntellectNone"
	MODIFIER_PROPERTY_STATS_INTELLECT_NONE = 110,
	// MScriptDescription = "GetModifierCastRangeBonus"
	MODIFIER_PROPERTY_CAST_RANGE_BONUS = 111,
	// MScriptDescription = "GetModifierCastRangeBonusPercentage"
	MODIFIER_PROPERTY_CAST_RANGE_BONUS_PERCENTAGE = 112,
	// MScriptDescription = "GetModifierCastRangeBonusTarget"
	MODIFIER_PROPERTY_CAST_RANGE_BONUS_TARGET = 113,
	// MScriptDescription = "GetModifierCastRangeBonusStacking"
	MODIFIER_PROPERTY_CAST_RANGE_BONUS_STACKING = 114,
	// MScriptDescription = "GetModifierAttackRangeOverride"
	MODIFIER_PROPERTY_ATTACK_RANGE_BASE_OVERRIDE = 115,
	// MScriptDescription = "GetModifierAttackRangeBonus"
	MODIFIER_PROPERTY_ATTACK_RANGE_BONUS = 116,
	// MScriptDescription = "GetModifierAttackRangeBonusUnique"
	MODIFIER_PROPERTY_ATTACK_RANGE_BONUS_UNIQUE = 117,
	// MScriptDescription = "GetModifierAttackRangeBonusPercentage"
	MODIFIER_PROPERTY_ATTACK_RANGE_BONUS_PERCENTAGE = 118,
	// MScriptDescription = "GetModifierMaxAttackRange"
	MODIFIER_PROPERTY_MAX_ATTACK_RANGE = 119,
	// MScriptDescription = "GetModifierProjectileSpeedBonus"
	MODIFIER_PROPERTY_PROJECTILE_SPEED_BONUS = 120,
	// MScriptDescription = "GetModifierProjectileSpeedBonusPercentage"
	MODIFIER_PROPERTY_PROJECTILE_SPEED_BONUS_PERCENTAGE = 121,
	// MScriptDescription = "GetModifierProjectileName"
	MODIFIER_PROPERTY_PROJECTILE_NAME = 122,
	// MScriptDescription = "ReincarnateTime"
	MODIFIER_PROPERTY_REINCARNATION = 123,
	// MScriptDescription = "ReincarnateSuppressFX"
	MODIFIER_PROPERTY_REINCARNATION_SUPPRESS_FX = 124,
	// MScriptDescription = "GetModifierConstantRespawnTime"
	MODIFIER_PROPERTY_RESPAWNTIME = 125,
	// MScriptDescription = "GetModifierPercentageRespawnTime"
	MODIFIER_PROPERTY_RESPAWNTIME_PERCENTAGE = 126,
	// MScriptDescription = "GetModifierStackingRespawnTime"
	MODIFIER_PROPERTY_RESPAWNTIME_STACKING = 127,
	// MScriptDescription = "GetModifierPercentageCooldown"
	MODIFIER_PROPERTY_COOLDOWN_PERCENTAGE = 128,
	// MScriptDescription = "GetModifierPercentageCooldownOngoing"
	MODIFIER_PROPERTY_COOLDOWN_PERCENTAGE_ONGOING = 129,
	// MScriptDescription = "GetModifierPercentageCasttime"
	MODIFIER_PROPERTY_CASTTIME_PERCENTAGE = 130,
	// MScriptDescription = "GetModifierConstantCasttime"
	MODIFIER_PROPERTY_CASTTIME_CONSTANT = 131,
	// MScriptDescription = "GetModifierPercentageAttackAnimTime"
	MODIFIER_PROPERTY_ATTACK_ANIM_TIME_PERCENTAGE = 132,
	// MScriptDescription = "GetModifierPercentageManacost"
	MODIFIER_PROPERTY_MANACOST_PERCENTAGE = 133,
	// MScriptDescription = "GetModifierPercentageManacostStacking"
	MODIFIER_PROPERTY_MANACOST_PERCENTAGE_STACKING = 134,
	// MScriptDescription = "GetModifierPercentageHealthcost"
	MODIFIER_PROPERTY_HEALTHCOST_PERCENTAGE = 135,
	// MScriptDescription = "GetModifierPercentageHealthcostStacking"
	MODIFIER_PROPERTY_HEALTHCOST_PERCENTAGE_STACKING = 136,
	// MScriptDescription = "GetModifierConstantDeathGoldCost"
	MODIFIER_PROPERTY_DEATHGOLDCOST = 137,
	// MScriptDescription = "GetModifierPercentageDeathGoldCost"
	MODIFIER_PROPERTY_PERCENTAGE_DEATHGOLDCOST = 138,
	// MScriptDescription = "GetModifierPercentageExpRateBoost"
	MODIFIER_PROPERTY_EXP_RATE_BOOST = 139,
	// MScriptDescription = "GetModifierPercentageGoldRateBoost"
	MODIFIER_PROPERTY_GOLD_RATE_BOOST = 140,
	// MScriptDescription = "GetModifierPercentageKillAssistGoldBoost"
	MODIFIER_PROPERTY_KILL_ASSIST_GOLD_BOOST = 141,
	// MScriptDescription = "GetModifierPercentageConvertExpToGold"
	MODIFIER_PROPERTY_CONVERT_EXP_TO_GOLD_PCT = 142,
	// MScriptDescription = "GetModifierPreAttack_CriticalStrike"
	MODIFIER_PROPERTY_PREATTACK_CRITICALSTRIKE = 143,
	// MScriptDescription = "GetModifierPreAttack_Target_CriticalStrike"
	MODIFIER_PROPERTY_PREATTACK_TARGET_CRITICALSTRIKE = 144,
	// MScriptDescription = "GetModifierMagical_ConstantBlock"
	MODIFIER_PROPERTY_MAGICAL_CONSTANT_BLOCK = 145,
	// MScriptDescription = "GetModifierPhysical_ConstantBlock"
	MODIFIER_PROPERTY_PHYSICAL_CONSTANT_BLOCK = 146,
	// MScriptDescription = "GetModifierPhysical_ConstantBlockSpecial"
	MODIFIER_PROPERTY_PHYSICAL_CONSTANT_BLOCK_SPECIAL = 147,
	// MScriptDescription = "GetModifierPhysical_ConstantBlockBonus"
	MODIFIER_PROPERTY_PHYSICAL_CONSTANT_BLOCK_BONUS = 148,
	// MScriptDescription = "GetModifierInnateDamageBlockPctOverride"
	MODIFIER_PROPERTY_INNATE_DAMAGE_BLOCK_PCT_OVERRIDE = 149,
	// MScriptDescription = "GetModifierPhysical_ConstantBlockUnavoidablePreArmor"
	MODIFIER_PROPERTY_TOTAL_CONSTANT_BLOCK_UNAVOIDABLE_PRE_ARMOR = 150,
	// MScriptDescription = "GetModifierTotal_ConstantBlock"
	MODIFIER_PROPERTY_TOTAL_CONSTANT_BLOCK = 151,
	// MScriptDescription = "GetOverrideAnimation"
	MODIFIER_PROPERTY_OVERRIDE_ANIMATION = 152,
	// MScriptDescription = "GetOverrideAnimationRate"
	MODIFIER_PROPERTY_OVERRIDE_ANIMATION_RATE = 153,
	// MScriptDescription = "GetAbsorbSpell"
	MODIFIER_PROPERTY_ABSORB_SPELL = 154,
	// MScriptDescription = "GetReflectSpell"
	MODIFIER_PROPERTY_REFLECT_SPELL = 155,
	// MScriptDescription = "GetDisableAutoAttack"
	MODIFIER_PROPERTY_DISABLE_AUTOATTACK = 156,
	// MScriptDescription = "GetBonusDayVision"
	MODIFIER_PROPERTY_BONUS_DAY_VISION = 157,
	// MScriptDescription = "GetBonusDayVisionPercentage"
	MODIFIER_PROPERTY_BONUS_DAY_VISION_PERCENTAGE = 158,
	// MScriptDescription = "GetBonusNightVision"
	MODIFIER_PROPERTY_BONUS_NIGHT_VISION = 159,
	// MScriptDescription = "GetBonusNightVisionUnique"
	MODIFIER_PROPERTY_BONUS_NIGHT_VISION_UNIQUE = 160,
	// MScriptDescription = "GetBonusVisionPercentage"
	MODIFIER_PROPERTY_BONUS_VISION_PERCENTAGE = 161,
	// MScriptDescription = "GetFixedDayVision"
	MODIFIER_PROPERTY_FIXED_DAY_VISION = 162,
	// MScriptDescription = "GetFixedNightVision"
	MODIFIER_PROPERTY_FIXED_NIGHT_VISION = 163,
	// MScriptDescription = "GetMinHealth"
	MODIFIER_PROPERTY_MIN_HEALTH = 164,
	// MScriptDescription = "GetMinMana"
	MODIFIER_PROPERTY_MIN_MANA = 165,
	// MScriptDescription = "GetAbsoluteNoDamagePhysical"
	MODIFIER_PROPERTY_ABSOLUTE_NO_DAMAGE_PHYSICAL = 166,
	// MScriptDescription = "GetAbsoluteNoDamageMagical"
	MODIFIER_PROPERTY_ABSOLUTE_NO_DAMAGE_MAGICAL = 167,
	// MScriptDescription = "GetAbsoluteNoDamagePure"
	MODIFIER_PROPERTY_ABSOLUTE_NO_DAMAGE_PURE = 168,
	// MScriptDescription = "GetIsIllusion"
	MODIFIER_PROPERTY_IS_ILLUSION = 169,
	// MScriptDescription = "GetModifierIllusionLabel"
	MODIFIER_PROPERTY_ILLUSION_LABEL = 170,
	// MScriptDescription = "GetModifierStrongIllusion"
	MODIFIER_PROPERTY_STRONG_ILLUSION = 171,
	// MScriptDescription = "GetModifierSuperIllusion"
	MODIFIER_PROPERTY_SUPER_ILLUSION = 172,
	// MScriptDescription = "GetModifierSuperIllusionWithUltimate"
	MODIFIER_PROPERTY_SUPER_ILLUSION_WITH_ULTIMATE = 173,
	// MScriptDescription = "GetModifierXPDuringDeath"
	MODIFIER_PROPERTY_XP_DURING_DEATH = 174,
	// MScriptDescription = "GetModifierTurnRate_Percentage"
	MODIFIER_PROPERTY_TURN_RATE_PERCENTAGE = 175,
	// MScriptDescription = "GetModifierTurnRate_Override"
	MODIFIER_PROPERTY_TURN_RATE_OVERRIDE = 176,
	// MScriptDescription = "GetDisableHealing"
	MODIFIER_PROPERTY_DISABLE_HEALING = 177,
	// MScriptDescription = "GetDisableManaGain"
	MODIFIER_PROPERTY_DISABLE_MANA_GAIN = 178,
	// MScriptDescription = "GetAlwaysAllowAttack"
	MODIFIER_PROPERTY_ALWAYS_ALLOW_ATTACK = 179,
	// MScriptDescription = "GetAllowEtherealAttack"
	MODIFIER_PROPERTY_ALWAYS_ETHEREAL_ATTACK = 180,
	// MScriptDescription = "GetOverrideAttackMagical"
	MODIFIER_PROPERTY_OVERRIDE_ATTACK_MAGICAL = 181,
	// MScriptDescription = "GetModifierUnitStatsNeedsRefresh"
	MODIFIER_PROPERTY_UNIT_STATS_NEEDS_REFRESH = 182,
	// MScriptDescription = "Unused"
	MODIFIER_PROPERTY_BOUNTY_CREEP_MULTIPLIER = 183,
	// MScriptDescription = "Unused"
	MODIFIER_PROPERTY_BOUNTY_OTHER_MULTIPLIER = 184,
	// MScriptDescription = "GetModifierUnitDisllowUpgrading"
	MODIFIER_PROPERTY_UNIT_DISALLOW_UPGRADING = 185,
	// MScriptDescription = "GetModifierDodgeProjectile"
	MODIFIER_PROPERTY_DODGE_PROJECTILE = 186,
	// MScriptDescription = "GetTriggerCosmeticAndEndAttack"
	MODIFIER_PROPERTY_TRIGGER_COSMETIC_AND_END_ATTACK = 187,
	// MScriptDescription = "GetPrimaryStatDamageMultiplier"
	MODIFIER_PROPERTY_PRIMARY_STAT_DAMAGE_MULTIPLIER = 188,
	// MScriptDescription = "GetModifierPreAttack_DeadlyBlow"
	MODIFIER_PROPERTY_PREATTACK_DEADLY_BLOW = 189,
	// MScriptDescription = "GetAlwaysAutoAttackWhileHoldPosition"
	MODIFIER_PROPERTY_ALWAYS_AUTOATTACK_WHILE_HOLD_POSITION = 190,
	// MScriptDescription = "GetPhysicalArmorPiercingPercentageTarget"
	MODIFIER_PROPERTY_PHYSICAL_ARMOR_PIERCING_PERCENTAGE_TARGET = 191,
	// MScriptDescription = "GetMagicalArmorPiercingPercentageTarget"
	MODIFIER_PROPERTY_MAGICAL_ARMOR_PIERCING_PERCENTAGE_TARGET = 192,
	// MScriptDescription = "GetCriticalStrikeBonus"
	MODIFIER_PROPERTY_CRITICAL_STRIKE_BONUS = 193,
	// MScriptDescription = "GetConvertAttackPhysicalToPure"
	MODIFIER_PROPERTY_CONVERT_ATTACK_PHYSICAL_TO_PURE = 194,
	// MScriptDescription = "GetBuffAmplification"
	MODIFIER_PROPERTY_BUFF_AMPLIFICATION = 195,
	// MScriptDescription = "OnSpellTargetReady"
	MODIFIER_EVENT_ON_SPELL_TARGET_READY = 196,
	// MScriptDescription = "OnAttackRecord"
	MODIFIER_EVENT_ON_ATTACK_RECORD = 197,
	// MScriptDescription = "OnAttackStart"
	MODIFIER_EVENT_ON_ATTACK_START = 198,
	// MScriptDescription = "OnAttack"
	MODIFIER_EVENT_ON_ATTACK = 199,
	// MScriptDescription = "OnAttackLanded"
	MODIFIER_EVENT_ON_ATTACK_LANDED = 200,
	// MScriptDescription = "OnAttackFail"
	MODIFIER_EVENT_ON_ATTACK_FAIL = 201,
	// MScriptDescription = "OnAttackAllied"
	MODIFIER_EVENT_ON_ATTACK_ALLIED = 202,
	// MScriptDescription = "OnProjectileDodge"
	MODIFIER_EVENT_ON_PROJECTILE_DODGE = 203,
	// MScriptDescription = "OnOrder"
	MODIFIER_EVENT_ON_ORDER = 204,
	// MScriptDescription = "OnOrderReceived"
	MODIFIER_EVENT_ON_ORDER_RECEIVED = 205,
	// MScriptDescription = "OnUnitMoved"
	MODIFIER_EVENT_ON_UNIT_MOVED = 206,
	// MScriptDescription = "OnAbilityStart"
	MODIFIER_EVENT_ON_ABILITY_START = 207,
	// MScriptDescription = "OnAbilityExecuted"
	MODIFIER_EVENT_ON_ABILITY_EXECUTED = 208,
	// MScriptDescription = "OnAbilityFullyCast"
	MODIFIER_EVENT_ON_ABILITY_FULLY_CAST = 209,
	// MScriptDescription = "OnBreakInvisibility"
	MODIFIER_EVENT_ON_BREAK_INVISIBILITY = 210,
	// MScriptDescription = "OnAbilityEndChannel"
	MODIFIER_EVENT_ON_ABILITY_END_CHANNEL = 211,
	// MScriptDescription = "Unused"
	MODIFIER_EVENT_ON_PROCESS_UPGRADE = 212,
	// MScriptDescription = "Unused"
	MODIFIER_EVENT_ON_REFRESH = 213,
	// MScriptDescription = "OnTakeDamage"
	MODIFIER_EVENT_ON_TAKEDAMAGE = 214,
	// MScriptDescription = "OnDamagePrevented"
	MODIFIER_EVENT_ON_DEATH_PREVENTED = 215,
	// MScriptDescription = "OnStateChanged"
	MODIFIER_EVENT_ON_STATE_CHANGED = 216,
	// MScriptDescription = "Unused"
	MODIFIER_EVENT_ON_ORB_EFFECT = 217,
	// MScriptDescription = "OnProcessCleave"
	MODIFIER_EVENT_ON_PROCESS_CLEAVE = 218,
	// MScriptDescription = "OnDamageCalculated"
	MODIFIER_EVENT_ON_DAMAGE_CALCULATED = 219,
	// MScriptDescription = "OnMagicDamageCalculated"
	MODIFIER_EVENT_ON_MAGIC_DAMAGE_CALCULATED = 220,
	// MScriptDescription = "OnAttacked"
	MODIFIER_EVENT_ON_ATTACKED = 221,
	// MScriptDescription = "OnDeath"
	MODIFIER_EVENT_ON_DEATH = 222,
	// MScriptDescription = "OnDeathCompleted"
	MODIFIER_EVENT_ON_DEATH_COMPLETED = 223,
	// MScriptDescription = "OnRespawn"
	MODIFIER_EVENT_ON_RESPAWN = 224,
	// MScriptDescription = "OnSpentMana"
	MODIFIER_EVENT_ON_SPENT_MANA = 225,
	// MScriptDescription = "OnSpentHealth"
	MODIFIER_EVENT_ON_SPENT_HEALTH = 226,
	// MScriptDescription = "OnSpentItemCharge"
	MODIFIER_EVENT_ON_SPENT_ITEM_CHARGE = 227,
	// MScriptDescription = "OnTeleporting"
	MODIFIER_EVENT_ON_TELEPORTING = 228,
	// MScriptDescription = "OnTeleported"
	MODIFIER_EVENT_ON_TELEPORTED = 229,
	// MScriptDescription = "OnSetLocation"
	MODIFIER_EVENT_ON_SET_LOCATION = 230,
	// MScriptDescription = "OnHealthGained"
	MODIFIER_EVENT_ON_HEALTH_GAINED = 231,
	// MScriptDescription = "OnManaGained"
	MODIFIER_EVENT_ON_MANA_GAINED = 232,
	// MScriptDescription = "OnTakeDamageKillCredit"
	MODIFIER_EVENT_ON_TAKEDAMAGE_KILLCREDIT = 233,
	// MScriptDescription = "OnHeroKilled"
	MODIFIER_EVENT_ON_HERO_KILLED = 234,
	// MScriptDescription = "OnHealReceived"
	MODIFIER_EVENT_ON_HEAL_RECEIVED = 235,
	// MScriptDescription = "OnRedirectHealthGain"
	MODIFIER_EVENT_ON_REDIRECT_HEALTH_GAIN = 236,
	// MScriptDescription = "OnBuildingKilled"
	MODIFIER_EVENT_ON_BUILDING_KILLED = 237,
	// MScriptDescription = "OnModelChanged"
	MODIFIER_EVENT_ON_MODEL_CHANGED = 238,
	// MScriptDescription = "OnModifierAdded"
	MODIFIER_EVENT_ON_MODIFIER_ADDED = 239,
	// MScriptDescription = "OnModifierRemoved"
	MODIFIER_EVENT_ON_MODIFIER_REMOVED = 240,
	// MScriptDescription = "OnScepterUpgradeSelected"
	MODIFIER_EVENT_ON_SCEPTER_UPGRADE_SELECTED = 241,
	// MScriptDescription = "OnShardUpgradeSelected"
	MODIFIER_EVENT_ON_SHARD_UPGRADE_SELECTED = 242,
	// MScriptDescription = "OnTooltip"
	MODIFIER_PROPERTY_TOOLTIP = 243,
	// MScriptDescription = "GetModifierModelChange"
	MODIFIER_PROPERTY_MODEL_CHANGE = 244,
	// MScriptDescription = "GetModifierModelScale"
	MODIFIER_PROPERTY_MODEL_SCALE = 245,
	// MScriptDescription = "GetModifierModelScaleAnimateTime"
	MODIFIER_PROPERTY_MODEL_SCALE_ANIMATE_TIME = 246,
	// MScriptDescription = "GetModifierModelScaleUseInOutEase"
	MODIFIER_PROPERTY_MODEL_SCALE_USE_IN_OUT_EASE = 247,
	// MScriptDescription = "GetModifierModelScaleConstant"
	MODIFIER_PROPERTY_MODEL_SCALE_CONSTANT = 248,
	// MScriptDescription = "GetModifierScepter"
	MODIFIER_PROPERTY_IS_SCEPTER = 249,
	// MScriptDescription = "GetModifierShard"
	MODIFIER_PROPERTY_IS_SHARD = 250,
	// MScriptDescription = "GetModifierRadarCooldownReduction"
	MODIFIER_PROPERTY_RADAR_COOLDOWN_REDUCTION = 251,
	// MScriptDescription = "GetActivityTranslationModifiers"
	MODIFIER_PROPERTY_TRANSLATE_ACTIVITY_MODIFIERS = 252,
	// MScriptDescription = "GetAttackSound"
	MODIFIER_PROPERTY_TRANSLATE_ATTACK_SOUND = 253,
	// MScriptDescription = "GetUnitLifetimeFraction"
	MODIFIER_PROPERTY_LIFETIME_FRACTION = 254,
	// MScriptDescription = "GetModifierProvidesFOWVision"
	MODIFIER_PROPERTY_PROVIDES_FOW_POSITION = 255,
	// MScriptDescription = "GetModifierSpellsRequireHP"
	MODIFIER_PROPERTY_SPELLS_REQUIRE_HP = 256,
	// MScriptDescription = "GetModifierConvertManaCostToHealthCost"
	MODIFIER_PROPERTY_CONVERT_MANA_COST_TO_HEALTH_COST = 257,
	// MScriptDescription = "GetForceDrawOnMinimap"
	MODIFIER_PROPERTY_FORCE_DRAW_MINIMAP = 258,
	// MScriptDescription = "GetModifierDisableTurning"
	MODIFIER_PROPERTY_DISABLE_TURNING = 259,
	// MScriptDescription = "GetModifierIgnoreCastAngle"
	MODIFIER_PROPERTY_IGNORE_CAST_ANGLE = 260,
	// MScriptDescription = "GetModifierChangeAbilityValue"
	MODIFIER_PROPERTY_CHANGE_ABILITY_VALUE = 261,
	// MScriptDescription = "GetModifierOverrideAbilitySpecial"
	MODIFIER_PROPERTY_OVERRIDE_ABILITY_SPECIAL = 262,
	// MScriptDescription = "GetModifierOverrideAbilitySpecialValue"
	MODIFIER_PROPERTY_OVERRIDE_ABILITY_SPECIAL_VALUE = 263,
	// MScriptDescription = "GetModifierAbilityLayout"
	MODIFIER_PROPERTY_ABILITY_LAYOUT = 264,
	// MScriptDescription = "OnDominated"
	MODIFIER_EVENT_ON_DOMINATED = 265,
	// MScriptDescription = "OnKill"
	MODIFIER_EVENT_ON_KILL = 266,
	// MScriptDescription = "OnAssist"
	MODIFIER_EVENT_ON_ASSIST = 267,
	// MScriptDescription = "GetModifierTempestDouble"
	MODIFIER_PROPERTY_TEMPEST_DOUBLE = 268,
	// MScriptDescription = "PreserveParticlesOnModelChanged"
	MODIFIER_PROPERTY_PRESERVE_PARTICLES_ON_MODEL_CHANGE = 269,
	// MScriptDescription = "OnAttackFinished"
	MODIFIER_EVENT_ON_ATTACK_FINISHED = 270,
	// MScriptDescription = "GetModifierIgnoreCooldown"
	MODIFIER_PROPERTY_IGNORE_COOLDOWN = 271,
	// MScriptDescription = "GetModifierCanAttackTrees"
	MODIFIER_PROPERTY_CAN_ATTACK_TREES = 272,
	// MScriptDescription = "GetVisualZDelta"
	MODIFIER_PROPERTY_VISUAL_Z_DELTA = 273,
	// MScriptDescription = "GetVisualZSpeedBaseOverride"
	MODIFIER_PROPERTY_VISUAL_Z_SPEED_BASE_OVERRIDE = 274,
	// MScriptDescription = ""
	MODIFIER_PROPERTY_INCOMING_DAMAGE_ILLUSION = 275,
	// MScriptDescription = "GetModifierNoVisionOfAttacker"
	MODIFIER_PROPERTY_DONT_GIVE_VISION_OF_ATTACKER = 276,
	// MScriptDescription = "OnTooltip2"
	MODIFIER_PROPERTY_TOOLTIP2 = 277,
	// MScriptDescription = "OnAttackRecordDestroy"
	MODIFIER_EVENT_ON_ATTACK_RECORD_DESTROY = 278,
	// MScriptDescription = "OnProjectileObstructionHit"
	MODIFIER_EVENT_ON_PROJECTILE_OBSTRUCTION_HIT = 279,
	// MScriptDescription = "GetSuppressTeleport"
	MODIFIER_PROPERTY_SUPPRESS_TELEPORT = 280,
	// MScriptDescription = "OnAttackCancelled"
	MODIFIER_EVENT_ON_ATTACK_CANCELLED = 281,
	// MScriptDescription = "GetSuppressCleave"
	MODIFIER_PROPERTY_SUPPRESS_CLEAVE = 282,
	// MScriptDescription = "BotAttackScoreBonus"
	MODIFIER_PROPERTY_BOT_ATTACK_SCORE_BONUS = 283,
	// MScriptDescription = "GetModifierAttackSpeedReductionPercentage"
	MODIFIER_PROPERTY_ATTACKSPEED_REDUCTION_PERCENTAGE = 284,
	// MScriptDescription = "GetModifierMoveSpeedReductionPercentage"
	MODIFIER_PROPERTY_MOVESPEED_REDUCTION_PERCENTAGE = 285,
	// MScriptDescription = ""
	MODIFIER_PROPERTY_ATTACK_WHILE_MOVING_TARGET = 286,
	// MScriptDescription = "GetModifierAttackSpeedPercentage"
	MODIFIER_PROPERTY_ATTACKSPEED_PERCENTAGE = 287,
	// MScriptDescription = "OnAttemptProjectileDodge"
	MODIFIER_EVENT_ON_ATTEMPT_PROJECTILE_DODGE = 288,
	// MScriptDescription = "GetModifierPercentageCooldownStacking"
	MODIFIER_PROPERTY_COOLDOWN_PERCENTAGE_STACKING = 289,
	// MScriptDescription = "GetModifierSpellRedirectTarget"
	MODIFIER_PROPERTY_SPELL_REDIRECT_TARGET = 290,
	// MScriptDescription = "GetModifierTurnRateConstant"
	MODIFIER_PROPERTY_TURN_RATE_CONSTANT = 291,
	// MScriptDescription = "GetModifierIsPackRat"
	MODIFIER_PROPERTY_PACK_RAT = 292,
	// MScriptDescription = "GetModifierPhysicalDamageOutgoing_Percentage"
	MODIFIER_PROPERTY_PHYSICALDAMAGEOUTGOING_PERCENTAGE = 293,
	// MScriptDescription = "GetModifierKnockbackAmplification_Percentage"
	MODIFIER_PROPERTY_KNOCKBACK_AMPLIFICATION_PERCENTAGE = 294,
	// MScriptDescription = "GetModifierHealthBarPips"
	MODIFIER_PROPERTY_HEALTHBAR_PIPS = 295,
	// MScriptDescription = "GetModifierIncomingDamageConstant"
	MODIFIER_PROPERTY_INCOMING_DAMAGE_CONSTANT = 296,
	// MScriptDescription = "OnSpellAppliedSuccessfully"
	MODIFIER_EVENT_SPELL_APPLIED_SUCCESSFULLY = 297,
	// MScriptDescription = "GetModifierAvoidDamageAfterReductions"
	MODIFIER_PROPERTY_AVOID_DAMAGE_AFTER_REDUCTIONS = 298,
	// MScriptDescription = "GetModifierPropetyFailAttack"
	MODIFIER_PROPERTY_FAIL_ATTACK = 299,
	// MScriptDescription = "GetModifierPrereduceIncomingDamage_Mult"
	MODIFIER_PROPERTY_PREREDUCE_INCOMING_DAMAGE_MULT = 300,
	// MScriptDescription = "GetModifierSuppressFullscreenDeathFX"
	MODIFIER_PROPERTY_SUPPRESS_FULLSCREEN_DEATH_FX = 301,
	// MScriptDescription = "MODIFIER_PROPERTY_INCOMING_DAMAGE_CONSTANT_POST"
	MODIFIER_PROPERTY_INCOMING_DAMAGE_CONSTANT_POST = 302,
	// MScriptDescription = "GetModifierDamageOutgoing_PercentageMultiplicative"
	MODIFIER_PROPERTY_DAMAGEOUTGOING_PERCENTAGE_MULTIPLICATIVE = 303,
	// MScriptDescription = "GetModifierTickGold_Multiplier"
	MODIFIER_PROPERTY_TICK_GOLD_MULTIPLIER = 304,
	// MScriptDescription = "GEtModifierSlowResistance_Unique"
	MODIFIER_PROPERTY_SLOW_RESISTANCE_UNIQUE = 305,
	// MScriptDescription = "GetModifierSlowResistance_Stacking"
	MODIFIER_PROPERTY_SLOW_RESISTANCE_STACKING = 306,
	// MScriptDescription = "GetModifierSlowResistanceAppliesToAttacks"
	MODIFIER_PROPERTY_SLOW_RESISTANCE_APPLIES_TO_ATTACKS = 307,
	// MScriptDescription = "GetModifierAoEBonusPercentage"
	MODIFIER_PROPERTY_AOE_BONUS_PERCENTAGE = 308,
	// MScriptDescription = "GetModifierProjectileSpeed"
	MODIFIER_PROPERTY_PROJECTILE_SPEED = 309,
	// MScriptDescription = "GetModifierProjectileSpeedTarget"
	MODIFIER_PROPERTY_PROJECTILE_SPEED_TARGET = 310,
	// MScriptDescription = "GetModifierBecomeStrength"
	MODIFIER_PROPERTY_BECOME_STRENGTH = 311,
	// MScriptDescription = "GetModifierBecomeAgility"
	MODIFIER_PROPERTY_BECOME_AGILITY = 312,
	// MScriptDescription = "GetModifierBecomeIntelligence"
	MODIFIER_PROPERTY_BECOME_INTELLIGENCE = 313,
	// MScriptDescription = "GetModifierBecomeUniversal"
	MODIFIER_PROPERTY_BECOME_UNIVERSAL = 314,
	// MScriptDescription = "OnForceProcMagicStick"
	MODIFIER_EVENT_ON_FORCE_PROC_MAGIC_STICK = 315,
	// MScriptDescription = "OnDamageHPLoss"
	MODIFIER_EVENT_ON_DAMAGE_HPLOSS = 316,
	// MScriptDescription = "GetModifierShareXPRune"
	MODIFIER_PROPERTY_SHARE_XPRUNE = 317,
	// MScriptDescription = "GetModifierXPFountainCountdownTimeOverride"
	MODIFIER_PROPERTY_XP_FOUNTAIN_COUNTDOWN_TIME_OVERRIDE = 318,
	// MScriptDescription = "GetModifierNoFreeTPScrollOnDeath"
	MODIFIER_PROPERTY_NO_FREE_TP_SCROLL_ON_DEATH = 319,
	// MScriptDescription = "GetModifierHasBonusNeutralItemChoice"
	MODIFIER_PROPERTY_HAS_BONUS_NEUTRAL_ITEM_CHOICE = 320,
	// MScriptDescription = "HasBonusNeutralItemPassive"
	MODIFIER_PROPERTY_HAS_BONUS_NEUTRAL_ITEM_PASSIVE = 321,
	// MScriptDescription = "GetModifierPreserveNeutralItemPassives"
	MODIFIER_PROPERTY_PRESERVE_NEUTRAL_ITEM_PASSIVES = 322,
	// MScriptDescription = "GetModifierForceMaxHealth"
	MODIFIER_PROPERTY_FORCE_MAX_HEALTH = 323,
	// MScriptDescription = "GetModifierForceMaxMana"
	MODIFIER_PROPERTY_FORCE_MAX_MANA = 324,
	// MScriptDescription = "GetModifierAoEBonusConstant"
	MODIFIER_PROPERTY_AOE_BONUS_CONSTANT = 325,
	// MScriptDescription = "GetModifierAoEBonusConstantStacking"
	MODIFIER_PROPERTY_AOE_BONUS_CONSTANT_STACKING = 326,
	// MScriptDescription = "OnTakeDamagePostUnavoidableBlock"
	MODIFIER_EVENT_ON_TAKEDAMAGE_POST_UNAVOIDABLE_BLOCK = 327,
	// MScriptDescription = "OnMuteDamageAbilities"
	MODIFIER_EVENT_ON_MUTE_DAMAGE_ABILITIES = 328,
	// MScriptDescription = "GetSuppressCrit"
	MODIFIER_PROPERTY_SUPPRESS_CRIT = 329,
	// MScriptDescription = "GetModifierAbilityPoints"
	MODIFIER_PROPERTY_ABILITY_POINTS = 330,
	// MScriptDescription = "GetModifierBuybackPenaltyPercent"
	MODIFIER_PROPERTY_BUYBACK_PENALTY_PERCENT = 331,
	// MScriptDescription = "GetModifierItemSellbackCost"
	MODIFIER_PROPERTY_ITEM_SELLBACK_COST = 332,
	// MScriptDescription = "GetModifierDisassembleAnything"
	MODIFIER_PROPERTY_DISASSEMBLE_ANYTHING = 333,
	// MScriptDescription = "GetModifierFixedManaRegen"
	MODIFIER_PROPERTY_FIXED_MANA_REGEN = 334,
	// MScriptDescription = "GetModifierBonusUphillMissChance"
	MODIFIER_PROPERTY_BONUS_UPHILL_MISS_CHANCE = 335,
	// MScriptDescription = "GetModifierCreepDenyPercent"
	MODIFIER_PROPERTY_CREEP_DENY_PERCENT = 336,
	// MScriptDescription = "GetModifierAttackSpeedAbsoluteMax"
	MODIFIER_PROPERTY_ATTACKSPEED_ABSOLUTE_MAX = 337,
	// MScriptDescription = "GetModifierFoWTeam"
	MODIFIER_PROPERTY_FOW_TEAM = 338,
	// MScriptDescription = "OnHeroBeginDying"
	MODIFIER_EVENT_ON_HERO_BEGIN_DYING = 339,
	// MScriptDescription = "GetModifierBonusLotusHeal"
	MODIFIER_PROPERTY_BONUS_LOTUS_HEAL = 340,
	// MScriptDescription = "GetModifierBaseHpRegenPerStrBonusPercentage"
	MODIFIER_PROPERTY_BASE_HP_REGEN_PER_STR_BONUS_PERCENTAGE = 341,
	// MScriptDescription = "GetModifierBaseArmorPerAgiBonusPercentage"
	MODIFIER_PROPERTY_BASE_ARMOR_PER_AGI_BONUS_PERCENTAGE = 342,
	// MScriptDescription = "GetModifierBaseAttackSpeedPerAgiBonusPercentage"
	MODIFIER_PROPERTY_BASE_ATTACKSPEED_PER_AGI_BONUS_PERCENTAGE = 343,
	// MScriptDescription = "GetModifierBaseManaRegenPerIntBonusPercentage"
	MODIFIER_PROPERTY_BASE_MP_REGEN_PER_INT_BONUS_PERCENTAGE = 344,
	// MScriptDescription = "GetModifierBaseMagicResistPerIntBonusPercentage"
	MODIFIER_PROPERTY_BASE_MRES_PER_INT_BONUS_PERCENTAGE = 345,
	// MScriptDescription = "OnDayStarted"
	MODIFIER_EVENT_ON_DAY_STARTED = 346,
	// MScriptDescription = "OnNightStarted"
	MODIFIER_EVENT_ON_NIGHT_STARTED = 347,
	// MScriptDescription = "GetModifierCreateBonusIllusionChance"
	MODIFIER_PROPERTY_CREATE_BONUS_ILLUSION_CHANCE = 348,
	// MScriptDescription = "GetModifierCreateBonusIllusionCount"
	MODIFIER_PROPERTY_CREATE_BONUS_ILLUSION_COUNT = 349,
	// MScriptDescription = "GetModofierPropertyPseudoRandomBonus"
	MODIFIER_PROPERTY_PSEUDORANDOM_BONUS = 350,
	// MScriptDescription = "GetModifierAttackHeightBonus"
	MODIFIER_PROPERTY_ATTACK_HEIGHT_BONUS = 351,
	// MScriptDescription = "GetSkipAttackRegulator"
	MODIFIER_PROPERTY_SKIP_ATTACK_REGULATOR = 352,
	// MScriptDescription = "GetModifierMiss_Percentage_Target"
	MODIFIER_PROPERTY_MISS_PERCENTAGE_TARGET = 353,
	// MScriptDescription = "GetModifierAdditionalNutralItemDrops"
	MODIFIER_PROPERTY_ADDITIONAL_NEUTRAL_ITEM_DROPS = 354,
	// MScriptDescription = "GetModifierKillStreakBonusGoldPercentage"
	MODIFIER_PROPERTY_KILL_STREAK_BONUS_GOLD_PERCENTAGE = 355,
	// MScriptDescription = "GetModifierHPRegenMultiplierPreAmplification"
	MODIFIER_PROPERTY_HP_REGEN_MULTIPLIER_PRE_AMPLIFICATION = 356,
	// MScriptDescription = "GetModifierHeroFacetOverride"
	MODIFIER_PROPERTY_HEROFACET_OVERRIDE = 357,
	// MScriptDescription = "OnTreeCutDown"
	MODIFIER_EVENT_ON_TREE_CUT_DOWN = 358,
	// MScriptDescription = "OnCleaveAttackLanded"
	MODIFIER_EVENT_ON_CLEAVE_ATTACK_LANDED = 359,
	// MScriptDescription = "MinAttributeLevel"
	MODIFIER_PROPERTY_MIN_ATTRIBUTE_LEVEL = 360,
	// MScriptDescription = "GetTierTokenReroll"
	MODIFIER_PROPERTY_TIER_TOKEN_REROLL = 361,
	// MScriptDescription = "GetVisionDegreeRestriction"
	MODIFIER_PROPERTY_VISION_DEGREES_RESTRICTION = 362,
	// MScriptDescription = "GetModifierTotal_ConstantBlockStacking"
	MODIFIER_PROPERTY_TOTAL_CONSTANT_BLOCK_STACKING = 363,
	// MScriptDescription = "GetModifierInventorySlotRestricted"
	MODIFIER_PROPERTY_INVENTORY_SLOT_RESTRICTED = 364,
	// MScriptDescription = "OnTierTokenRerolled"
	MODIFIER_EVENT_ON_TIER_TOKEN_REROLLED = 365,
	// MScriptDescription = "GetRedirectSpell"
	MODIFIER_PROPERTY_REDIRECT_SPELL = 366,
	// MScriptDescription = "GetBaseAttackPostBonus"
	MODIFIER_PROPERTY_BASEATTACK_POSTBONUS = 367,
	// MScriptDescription = "OnFoWTeamChanged"
	MODIFIER_EVENT_ON_FOW_TEAM_CHANGED = 368,
	// MScriptDescription = "GetSuppressAttackProcs"
	MODIFIER_PROPERTY_SUPPRESS_ATTACK_PROCS = 369,
	// MScriptDescription = "OnAbilityToggled"
	MODIFIER_EVENT_ON_ABILITY_TOGGLED = 370,
	// MScriptDescription = "GetModifierAvoidAttackProcs"
	MODIFIER_PROPERTY_AVOID_ATTACK_PROCS = 371,
	// MScriptDescription = "OnRuneSpawn"
	MODIFIER_EVENT_ON_RUNE_SPAWN = 372,
	// MScriptDescription = "GetModifierProperty_PhysicalLifesteal"
	MODIFIER_PROPERTY_PHYSICAL_LIFESTEAL = 373,
	// MScriptDescription = "GetModifierProperty_MagicalLifesteal"
	MODIFIER_PROPERTY_MAGICAL_LIFESTEAL = 374,
	// MScriptDescription = "OnPureDamageCalculated"
	MODIFIER_EVENT_ON_PURE_DAMAGE_CALCULATED = 375,
	// MScriptDescription = "GetModifierNeutralTrinketOptions"
	MODIFIER_EVENT_NEUTRAL_TRINKET_OPTIONS = 376,
	// MScriptDescription = "GetModifierNeutralEnhancementOptions"
	MODIFIER_EVENT_NEUTRAL_ENHANCEMENT_OPTIONS = 377,
	// MScriptDescription = "GetModifierMoveSpeedMax_BonusConstant"
	MODIFIER_PROPERTY_MOVESPEED_MAX_BONUS_CONSTANT = 378,
	// MScriptDescription = "GetModifierMoveSpeedPostMultiplierBonus_Constant"
	MODIFIER_PROPERTY_MOVESPEED_POST_MULTIPLIER_BONUS_CONSTANT = 379,
	// MScriptDescription = "GetModifierPropertyForbidIllusions"
	MODIFIER_PROPERTY_FORBID_ILLUSIONS = 380,
	// MScriptDescription = "GetModifierPropertyManacostOverride"
	MODIFIER_PROPERTY_MANACOST_OVERRIDE = 381,
	// MScriptDescription = "GetModifierPropertyRestorationAmplification"
	MODIFIER_PROPERTY_RESTORATION_AMPLIFICATION = 382,
	// MScriptDescription = "GetModifierPropertyRestorationAmplificationUnique"
	MODIFIER_PROPERTY_RESTORATION_AMPLIFICATION_UNIQUE = 383,
	// MScriptDescription = "GetModifierPropertyHealingAmplificationUnique"
	MODIFIER_PROPERTY_HEAL_AMPLIFY_PERCENTAGE_SOURCE_UNIQUE = 384,
	// MScriptDescription = "GetModifierPropertyRedirectHealthGain"
	MODIFIER_PROPERTY_REDIRECT_HEALTH_GAIN = 385,
	// MScriptDescription = "GetSuppressIncomingCrit"
	MODIFIER_PROPERTY_SUPPRESS_INCOMING_CRIT = 386,
	// MScriptDescription = "GetModifierPropertyUpgradeNeutralArtifacts"
	MODIFIER_PROPERTY_UPGRADE_NEUTRAL_ARTIFACTS = 387,
	// MScriptDescription = "GetModifierPropertySuppressInvalidMoveAttackOrders"
	MODIFIER_PROPERTY_SUPPRESS_INVALID_MOVE_ATTACK_ORDERS = 388,
	// MScriptDescription = "GetModifierPropertyConsumableUseSpeed"
	MODIFIER_PROPERTY_CONSUMABLE_USE_SPEED = 389,
	// MScriptDescription = "GetRequiredLevel"
	MODIFIER_PROPERTY_REQUIRED_LEVEL = 390,
	// MScriptDescription = "OnModifierRefreshed"
	MODIFIER_EVENT_ON_MODIFIER_REFRESHED = 391,
	// MScriptDescription = "OnAbilitySwapped"
	MODIFIER_EVENT_ON_ABILITY_SWAPPED = 392,
	// MScriptDescription = "GetModifierOverrideCreepBounty"
	MODIFIER_PROPERTY_OVERRIDE_CREEP_BOUNTY = 393,
	// MScriptDescription = "GetModifierOverrideBaseDamage"
	MODIFIER_PROPERTY_OVERRIDE_BASE_DAMAGE = 394,
	// MScriptDescription = "GetModifierOverrideUntargetableFrom"
	MODIFIER_PROPERTY_UNTARGETABLE_FROM = 395,
	// MScriptDescription = "GetModifierOverrideUntargetableTo"
	MODIFIER_PROPERTY_UNTARGETABLE_TO = 396,
	// MScriptDescription = "GetModifierSuperIllusionWithItems"
	MODIFIER_PROPERTY_SUPER_ILLUSION_WITH_ITEMS = 397,
	// MScriptDescription = "OnPurged"
	MODIFIER_EVENT_ON_PURGE = 398,
	// MScriptDescription = "OnIllusionCreated"
	MODIFIER_EVENT_ON_ILLUSION_CREATED = 399,
	// MScriptDescription = "GetModifierHeroLevelScale"
	MODIFIER_PROPERTY_HEROLEVELSCALE = 400,
	// MScriptDescription = "GetModifierReplaceAttack"
	MODIFIER_PROPERTY_REPLACE_ATTACK = 401,
	// MScriptDescription = "GetModifierPropertyCustom1"
	MODIFIER_PROPERTY_CUSTOM1 = 402,
	// MScriptDescription = "GetModifierPropertyCustom2"
	MODIFIER_PROPERTY_CUSTOM2 = 403,
	// MScriptDescription = "GetModifierPropertyCustom3"
	MODIFIER_PROPERTY_CUSTOM3 = 404,
	// MScriptDescription = "OnCustom1"
	MODIFIER_EVENT_ON_CUSTOM1 = 405,
	// MScriptDescription = "OnCustom2"
	MODIFIER_EVENT_ON_CUSTOM2 = 406,
	// MScriptDescription = "OnCustom3"
	MODIFIER_EVENT_ON_CUSTOM3 = 407,
	// MScriptDescription = "GetModifierPropertyIgnoreForceTarget"
	MODIFIER_PROPERTY_IGNORE_FORCE_ATTACK_TARGET = 408,
	MODIFIER_FUNCTION_LAST = 409,
	MODIFIER_FUNCTION_INVALID = 65535,
};
